import type Groq from "groq-sdk";

export const agentToolDefinitions: Groq.Chat.Completions.ChatCompletionTool[] = [
  { type: "function", function: { name: "create_financial_entity_draft", description: "Cria um rascunho para cadastrar salário, cartão, gasto fixo, empréstimo, reserva ou conta. Não aplica sem confirmação posterior.", parameters: { type: "object", properties: { kind: { type: "string", enum: ["income", "credit_card", "fixed_expense", "loan", "reserve", "account"] }, name: { type: "string" }, amountCents: { anyOf: [{ type: "integer", minimum: 0 }, { type: "null" }] }, effectiveFrom: { type: "string", description: "Mês inicial YYYY-MM" }, closingDay: { anyOf: [{ type: "integer", minimum: 1, maximum: 31 }, { type: "null" }] }, dueDay: { anyOf: [{ type: "integer", minimum: 1, maximum: 31 }, { type: "null" }] } }, required: ["kind", "name", "effectiveFrom"], additionalProperties: false } } },
  { type: "function", function: { name: "rename_financial_entity_draft", description: "Cria um rascunho para renomear uma entidade financeira existente, preservando o nome anterior como alias.", parameters: { type: "object", properties: { currentName: { type: "string" }, newName: { type: "string" } }, required: ["currentName", "newName"], additionalProperties: false } } },
  { type: "function", function: { name: "change_financial_entity_value_draft", description: "Cria um rascunho para alterar o valor recorrente de uma entidade a partir de um mês, preservando o histórico.", parameters: { type: "object", properties: { name: { type: "string" }, amountCents: { type: "integer", minimum: 0 }, effectiveFrom: { type: "string", description: "Mês inicial YYYY-MM" } }, required: ["name", "amountCents", "effectiveFrom"], additionalProperties: false } } },
  { type: "function", function: { name: "close_financial_entity_draft", description: "Cria um rascunho para encerrar ou quitar uma entidade a partir de um mês, sem apagar o histórico.", parameters: { type: "object", properties: { name: { type: "string" }, inactiveFrom: { type: "string", description: "Primeiro mês sem cobrança YYYY-MM" }, status: { type: "string", enum: ["inactive", "settled"] } }, required: ["name", "inactiveFrom", "status"], additionalProperties: false } } },
  { type: "function", function: { name: "cancel_financial_change", description: "Cancela o rascunho financeiro pendente mais recente desta conversa.", parameters: { type: "object", properties: { cancelled: { type: "boolean", enum: [true] } }, required: ["cancelled"], additionalProperties: false } } },
  { type: "function", function: { name: "confirm_financial_change", description: "Confirma o rascunho financeiro pendente mais recente desta conversa.", parameters: { type: "object", properties: { confirmed: { type: "boolean", enum: [true] } }, required: ["confirmed"], additionalProperties: false } } },
  { type: "function", function: { name: "query_financial_overview", description: "Consulta resumo, faturas e projeção de um mês disponível.", parameters: { type: "object", properties: { month: { type: "string", description: "Mês no formato YYYY-MM" } }, required: ["month"], additionalProperties: false } } },
  { type: "function", function: { name: "compare_financial_months", description: "Compara receitas, compromissos e saldo projetado de dois meses usando o motor financeiro.", parameters: { type: "object", properties: { monthA: { type: "string", description: "Primeiro mês YYYY-MM" }, monthB: { type: "string", description: "Segundo mês YYYY-MM" } }, required: ["monthA", "monthB"], additionalProperties: false } } },
  { type: "function", function: { name: "create_transaction_draft", description: "Cria prévia confirmável de despesa, receita avulsa, estorno ou transferência.", parameters: { type: "object", properties: { type: { type: "string", enum: ["expense", "income", "refund", "transfer"] }, amountCents: { type: "integer" }, description: { type: "string" }, category: { type: "string" }, paymentMethod: { type: "string" }, destinationPaymentMethod: { anyOf: [{ type: "string" }, { type: "null" }] }, installmentCount: { type: "integer", minimum: 1, maximum: 120 }, belongsToThirdParty: { type: "boolean" } }, required: ["type", "amountCents", "description", "category", "paymentMethod", "installmentCount", "belongsToThirdParty"], additionalProperties: false } } },
  { type: "function", function: { name: "confirm_transaction", description: "Valida a intenção de confirmar um rascunho. Nesta etapa ainda não persiste.", parameters: { type: "object", properties: { draftId: { type: "string" }, confirmed: { type: "boolean", enum: [true] } }, required: ["draftId", "confirmed"], additionalProperties: false } } },
  { type: "function", function: { name: "correct_latest_transaction_draft", description: "Prepara correção auditável do último lançamento: valor, categoria, descrição, data, meio de pagamento ou terceiro.", parameters: { type: "object", properties: { amountCents: { type: "integer", minimum: 1 }, category: { type: "string" }, description: { type: "string" }, occurredOn: { type: "string" }, paymentMethod: { type: "string" }, belongsToThirdParty: { type: "boolean" } }, additionalProperties: false } } },
  { type: "function", function: { name: "void_latest_transaction_draft", description: "Prepara o desfazimento lógico do último lançamento confirmado nesta conversa, sem apagar o histórico.", parameters: { type: "object", properties: { confirmedIntent: { type: "boolean", enum: [true] } }, required: ["confirmedIntent"], additionalProperties: false } } },
  { type: "function", function: { name: "anticipate_installments_draft", description: "Prepara a antecipação das últimas parcelas futuras do último lançamento parcelado.", parameters: { type: "object", properties: { count: { type: "integer", minimum: 1, maximum: 120 } }, required: ["count"], additionalProperties: false } } },
  { type: "function", function: { name: "query_transaction_history", description: "Consulta os lançamentos recentes, inclusive corrigidos ou desfeitos.", parameters: { type: "object", properties: { limit: { type: "integer", minimum: 1, maximum: 50 } }, required: ["limit"], additionalProperties: false } } },
  { type: "function", function: { name: "analyze_spending", description: "Compara gastos por categoria com os dois meses anteriores e encontra oportunidades de economia.", parameters: { type: "object", properties: { month: { type: "string", description: "Mês no formato YYYY-MM" } }, required: ["month"], additionalProperties: false } } },
  { type: "function", function: { name: "simulate_financial_scenario", description: "Simula o efeito de reduzir uma categoria sem alterar dados.", parameters: { type: "object", properties: { month: { type: "string" }, category: { type: "string" }, reductionPercentage: { type: "integer", minimum: 0, maximum: 100 } }, required: ["month", "category", "reductionPercentage"], additionalProperties: false } } },
];
